name: Check Website Availability

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every 24 hours at midnight UTC
  workflow_dispatch:  # Allows manual runs as well

jobs:
  check-website:
    runs-on: ubuntu-latest

    steps:
    - name: Check if site is online
      run: |
        URL="https://www.kdbespoke.co.uk"
        STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" "$URL")
        if [ "$STATUS_CODE" -ne 200 ]; then
          echo "Website is down (Status code: $STATUS_CODE)"
          exit 1
        else
          echo "Website is up (Status code: $STATUS_CODE)"
      ```

