name: Check Website Availability

on:
  workflow_dispatch:  # This enables manual runs
  schedule:
    - cron: '0 0 * * *'  # Optional: Runs daily at midnight UTC

jobs:
  check-website:
    runs-on: ubuntu-latest

    steps:
    - name: Check if site is online
      run: |
        URL="https://www.kdbespoke.co.uk"
        echo "Checking website status for $URL"

        # Use curl with additional options to follow redirects and ignore SSL issues
        STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" -L --max-time 10 "$URL")
        
        echo "Received status code: $STATUS_CODE"
        
        if [ "$STATUS_CODE" -ne 200 ]; then
          echo "Website is down or returned a non-200 status code: $STATUS_CODE"
          exit 1
        else:
          echo "Website is up and accessible (Status code: $STATUS_CODE)"
        fi
